import { StyleSheet } from 'react-native-unistyles';

export const stylesheet = StyleSheet.create((theme) => ({
    container: {
        flex: 1,
        backgroundColor: theme.colors.groupped.background,
    },
    loadingContainer: {
        flex: 1,
        alignItems: 'center',
        justifyContent: 'center',
    },
    header: {
        padding: 16,
        backgroundColor: theme.colors.surface,
        borderBottomWidth: 1,
        borderBottomColor: theme.colors.divider,
    },
    title: {
        fontSize: 20,
        fontWeight: 'bold',
        color: theme.colors.text,
        marginBottom: 4,
    },
    subtitle: {
        fontSize: 14,
        color: theme.colors.textSecondary,
    },
    boardContainer: {
        flex: 1,
        flexDirection: 'row',
        padding: 16,
    },
    column: {
        flex: 1,
        backgroundColor: theme.colors.groupped.background,
        borderRadius: 12,
        marginHorizontal: 6,
        padding: 12,
        borderWidth: 1,
        borderColor: theme.colors.divider,
    },
    columnHeader: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        marginBottom: 12,
    },
    columnHeaderLeft: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 8,
    },
    columnStatusDot: {
        width: 8,
        height: 8,
        borderRadius: 4,
    },
    columnTitle: {
        fontSize: 14,
        fontWeight: '600',
        color: theme.colors.text,
    },
    taskCount: {
        fontSize: 11,
        color: theme.colors.textSecondary,
        backgroundColor: theme.colors.surface,
        paddingHorizontal: 7,
        paddingVertical: 2,
        borderRadius: 10,
    },
    taskCard: {
        backgroundColor: theme.colors.surface,
        borderRadius: 12,
        padding: 12,
        paddingLeft: 15,
        // Force card to fill column width and constrain children
        width: '100%',
        overflow: 'hidden',
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 1 },
        shadowOpacity: 0.07,
        shadowRadius: 6,
        elevation: 2,
    },
    taskPriorityAccent: {
        position: 'absolute',
        left: 0,
        top: 0,
        bottom: 0,
        width: 3,
    },
    taskTitle: {
        fontSize: 14,
        color: theme.colors.text,
        marginBottom: 4,
        // Explicit width: 100% forces text to wrap within card boundaries
        width: '100%',
    },
    taskAssigneeRow: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 6,
        marginTop: 6,
    },
    taskAssigneeBadge: {
        width: 20,
        height: 20,
        borderRadius: 10,
        alignItems: 'center',
        justifyContent: 'center',
    },
    taskAssigneeBadgeText: {
        fontSize: 9,
        fontWeight: '700',
        color: '#FFFFFF',
    },
    taskAssigneeName: {
        fontSize: 11,
        color: theme.colors.textSecondary,
        fontWeight: '500',
    },
    taskAssignee: {
        fontSize: 12,
        color: theme.colors.textSecondary,
        fontStyle: 'italic',
    },
    taskReporter: {
        fontSize: 11,
        color: theme.colors.textSecondary,
        marginTop: 2,
    },
    taskCommentSummary: {
        fontSize: 11,
        color: theme.colors.text,
        marginTop: 6,
        lineHeight: 16,
    },
    taskHumanLockBadge: {
        flexDirection: 'row',
        alignItems: 'center',
        alignSelf: 'flex-start',
        gap: 4,
        marginTop: 8,
        paddingHorizontal: 8,
        paddingVertical: 4,
        borderRadius: 999,
        backgroundColor: 'rgba(255, 149, 0, 0.14)',
    },
    taskHumanLockText: {
        fontSize: 10,
        fontWeight: '600',
        color: '#C26A00',
    },
    taskMeta: {
        flexDirection: 'row',
        alignItems: 'center',
        marginTop: 8,
        paddingTop: 8,
        borderTopWidth: 1,
        borderTopColor: theme.colors.divider,
    },
    taskSessionsLink: {
        flexDirection: 'row',
        alignItems: 'center',
        marginRight: 12,
    },
    taskSessionsIcon: {
        marginRight: 4,
    },
    taskSessionsText: {
        fontSize: 11,
        color: theme.colors.textSecondary,
    },
    taskPriority: {
        fontSize: 10,
        paddingHorizontal: 6,
        paddingVertical: 2,
        borderRadius: 4,
        overflow: 'hidden',
    },
    taskActiveExecution: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 4,
        paddingHorizontal: 8,
        paddingVertical: 3,
        borderRadius: 999,
        backgroundColor: 'rgba(255, 149, 0, 0.18)',
        borderWidth: 1,
        borderColor: 'rgba(255, 149, 0, 0.32)',
    },
    taskActiveExecutionText: {
        fontSize: 10,
        fontWeight: '600',
        color: '#FF9500',
    },
    addTaskButton: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        padding: 8,
        marginTop: 8,
        borderWidth: 1,
        borderColor: theme.colors.divider,
        borderRadius: 8,
        borderStyle: 'dashed',
    },
    addTaskText: {
        fontSize: 14,
        color: theme.colors.textSecondary,
        marginLeft: 4,
    },
    // Pending tasks banner styles
    pendingBanner: {
        flexDirection: 'row',
        alignItems: 'center',
        padding: 12,
        marginHorizontal: 16,
        marginTop: 16,
        borderWidth: 1,
        borderRadius: 8,
    },
    pendingBannerText: {
        flex: 1,
        fontSize: 14,
        marginLeft: 8,
    },
    pendingBannerButton: {
        paddingHorizontal: 16,
        paddingVertical: 6,
        borderRadius: 6,
    },
    pendingBannerButtonText: {
        color: '#FFFFFF',
        fontSize: 14,
        fontWeight: '600',
    },
    scrollContent: {
        paddingBottom: 48
    },
    section: {
        marginTop: 16,
        backgroundColor: theme.colors.surface,
        borderRadius: 12,
        marginHorizontal: 16,
        padding: 16,
        borderWidth: 1,
        borderColor: theme.colors.divider,
    },
    sectionTitle: {
        fontSize: 16,
        fontWeight: '600',
        color: theme.colors.text,
        marginBottom: 12,
    },
    memberCard: {
        paddingVertical: 12,
        borderTopWidth: 1,
        borderTopColor: theme.colors.divider,
    },
    memberFirst: {
        borderTopWidth: 0,
        paddingTop: 4,
    },
    memberName: {
        fontSize: 15,
        fontWeight: '600',
        color: theme.colors.text,
    },
    memberMeta: {
        fontSize: 13,
        color: theme.colors.textSecondary,
        marginTop: 4,
    },
    pill: {
        alignSelf: 'flex-start',
        paddingHorizontal: 10,
        paddingVertical: 4,
        borderRadius: 999,
        backgroundColor: theme.colors.groupped.background,
        marginTop: 8,
    },
    pillText: {
        fontSize: 12,
        fontWeight: '500',
        color: theme.colors.textSecondary,
    },
    roleCard: {
        borderTopWidth: 1,
        borderTopColor: theme.colors.divider,
        paddingTop: 16,
        marginTop: 16,
    },
    roleTitle: {
        fontSize: 15,
        fontWeight: '600',
        color: theme.colors.text,
    },
    roleSummary: {
        fontSize: 13,
        color: theme.colors.textSecondary,
        marginTop: 6,
        lineHeight: 20,
    },
    metaLabel: {
        marginTop: 12,
        fontSize: 12,
        fontWeight: '600',
        color: theme.colors.textSecondary,
        textTransform: 'uppercase',
        letterSpacing: 0.5,
    },
    bulletItem: {
        fontSize: 13,
        color: theme.colors.text,
        marginTop: 6,
        lineHeight: 18,
    },
    agreementsRow: {
        flexDirection: 'row',
        flexWrap: 'wrap',
        gap: 12,
    },
    agreementCard: {
        flex: 1,
        minWidth: 150,
        borderWidth: 1,
        borderColor: theme.colors.divider,
        borderRadius: 10,
        padding: 12,
        marginTop: 12,
    },
    agreementTitle: {
        fontSize: 12,
        fontWeight: '600',
        color: theme.colors.textSecondary,
        textTransform: 'uppercase',
        letterSpacing: 0.5,
        marginBottom: 6,
    },
    agreementText: {
        fontSize: 13,
        color: theme.colors.text,
        lineHeight: 18,
    },
    showcaseCard: {
        borderWidth: 1,
        borderColor: theme.colors.divider,
        borderRadius: 14,
        padding: 14,
        marginTop: 12,
        backgroundColor: theme.colors.surface,
    },
    showcaseEyebrow: {
        fontSize: 11,
        fontWeight: '700',
        color: theme.colors.textSecondary,
        textTransform: 'uppercase',
        letterSpacing: 0.6,
        marginBottom: 8,
    },
    showcaseTitle: {
        fontSize: 16,
        fontWeight: '700',
        color: theme.colors.text,
    },
    showcaseLead: {
        fontSize: 13,
        color: theme.colors.textSecondary,
        marginTop: 8,
        lineHeight: 19,
    },
    promptLine: {
        fontSize: 13,
        color: theme.colors.text,
        lineHeight: 19,
        marginTop: 8,
    },
    reviewMetricsRow: {
        flexDirection: 'row',
        flexWrap: 'wrap',
        gap: 10,
        marginTop: 12,
    },
    reviewMetricCard: {
        minWidth: 120,
        paddingHorizontal: 12,
        paddingVertical: 10,
        borderRadius: 12,
        borderWidth: 1,
        borderColor: theme.colors.divider,
        backgroundColor: theme.colors.groupped.background,
    },
    reviewMetricLabel: {
        fontSize: 11,
        fontWeight: '600',
        color: theme.colors.textSecondary,
        textTransform: 'uppercase',
        letterSpacing: 0.5,
    },
    reviewMetricValue: {
        fontSize: 18,
        fontWeight: '700',
        color: theme.colors.text,
        marginTop: 6,
    },
    reviewMetaText: {
        fontSize: 12,
        color: theme.colors.textSecondary,
        marginTop: 10,
        lineHeight: 18,
    },
    reviewItemCard: {
        borderWidth: 1,
        borderColor: theme.colors.divider,
        borderRadius: 12,
        padding: 12,
        marginTop: 10,
        backgroundColor: theme.colors.surface,
    },
    reviewItemHeader: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        gap: 8,
    },
    reviewItemTitle: {
        fontSize: 13,
        fontWeight: '600',
        color: theme.colors.text,
        flex: 1,
    },
    reviewItemRating: {
        fontSize: 13,
        fontWeight: '700',
    },
    reviewItemComment: {
        fontSize: 13,
        color: theme.colors.textSecondary,
        lineHeight: 19,
        marginTop: 8,
    },
    emptyState: {
        fontSize: 13,
        color: theme.colors.textSecondary,
        fontStyle: 'italic',
    },
    desktopPanelHeader: {
        paddingHorizontal: 24,
        paddingVertical: 14,
        height: 54,
        borderBottomWidth: 1,
        borderBottomColor: '#DEE8EE',
        zIndex: 10,
    },
    desktopHeaderTopRow: {
        flex: 1,
        flexDirection: 'row',
        alignItems: 'center',
    },
    desktopTabsRow: {
        flexDirection: 'row',
        alignItems: 'center',
        height: '100%',
        minWidth: 0,
    },
    desktopTab: {
        width: 80,
        alignItems: 'center',
        justifyContent: 'center',
        height: '100%',
    },
    desktopTabActive: {
        borderRadius: 999,
        shadowColor: '#7A8C9B',
        shadowOffset: { width: 0, height: 3 },
        shadowOpacity: 0.07,
        shadowRadius: 10,
        elevation: 2,
    },
    desktopTabText: {
        fontSize: 13,
    },
    desktopPanelBody: {
        flex: 1,
        minHeight: 0,
        minWidth: 0,
    },
    desktopMenu: {
        position: 'absolute',
        top: 52,
        right: 22,
        minWidth: 188,
        borderRadius: 16,
        overflow: 'hidden',
        borderWidth: 1,
        shadowColor: '#000000',
        shadowOffset: { width: 0, height: 8 },
        shadowOpacity: 0.12,
        shadowRadius: 24,
        elevation: 6,
        zIndex: 1000,
    },
    desktopMenuItem: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 10,
        paddingHorizontal: 14,
        paddingVertical: 12,
    },
    desktopMenuDivider: {
        height: 1,
    },
    mobileHeaderTopRow: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 12,
        marginBottom: 12,
    },
    mobileWorkspaceButton: {
        flex: 1,
        flexDirection: 'row',
        alignItems: 'center',
        gap: 10,
        backgroundColor: theme.colors.groupped.background,
        borderWidth: 1,
        borderColor: theme.colors.divider,
        borderRadius: 14,
        paddingHorizontal: 12,
        paddingVertical: 10,
    },
    mobileWorkspaceCopy: {
        flex: 1,
        minWidth: 0,
    },
    mobileWorkspaceTitle: {
        fontSize: 13,
        fontWeight: '600',
        color: theme.colors.text,
    },
    mobileWorkspaceSubtitle: {
        fontSize: 11,
        color: theme.colors.textSecondary,
        marginTop: 2,
    },
    mobileHeaderIconButton: {
        width: 40,
        height: 40,
        borderRadius: 20,
        alignItems: 'center',
        justifyContent: 'center',
        backgroundColor: theme.colors.groupped.background,
        borderWidth: 1,
        borderColor: theme.colors.divider,
    },
    mobileWorkspaceBackdrop: {
        position: 'absolute',
        top: 0,
        left: 0,
        right: 0,
        bottom: 0,
        backgroundColor: 'rgba(10, 16, 22, 0.16)',
        zIndex: 1200,
    },
    mobileWorkspacePanel: {
        position: 'absolute',
        top: 82,
        left: 12,
        bottom: 16,
        borderRadius: 22,
        overflow: 'hidden',
        backgroundColor: '#F8FBFD',
        borderWidth: 1,
        borderColor: '#D9E4EA',
        shadowColor: '#000000',
        shadowOffset: { width: 0, height: 12 },
        shadowOpacity: 0.14,
        shadowRadius: 32,
        elevation: 12,
        zIndex: 1300,
    },
    agentsButton: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 4,
        paddingHorizontal: 10,
        paddingVertical: 6,
        borderRadius: 8,
        borderWidth: 1,
    },
    agentsButtonText: {
        fontSize: 13,
        fontWeight: '500',
    },
    floatingPanelBackdrop: {
        position: 'absolute',
        top: 0,
        left: 0,
        right: 0,
        bottom: 0,
        zIndex: 900,
    },
    floatingPanelAnchor: {
        position: 'absolute',
        right: 12,
        top: 56,
        zIndex: 1000,
        width: 320,
    },
    headerActionRow: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 8,
    },
}));
